AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Batch infrastructure for AI Videographer render jobs'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the compute environment
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the compute environment
  
  EcrImageUri:
    Type: String
    Default: '960446855965.dkr.ecr.ap-southeast-2.amazonaws.com/ai-videographer-worker:latest'
    Description: ECR image URI for the worker
  
  MaxvCpus:
    Type: Number
    Default: 16
    Description: Maximum vCPUs for the compute environment

Resources:
  # Security Group for Batch instances
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AI Videographer Batch instances
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: ai-videographer-batch-sg

  # IAM Role for Batch Service
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-videographer-batch-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  # IAM Role for ECS Task Execution (pulling images, CloudWatch logs)
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-videographer-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ai-videographer/*'

  # IAM Role for the Job (what the container can do)
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-videographer-batch-job-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # IAM Instance Profile for EC2 instances
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ai-videographer-batch-instance-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ai-videographer-batch-instance-profile
      Roles:
        - !Ref BatchInstanceRole

  # CloudWatch Log Group
  RenderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/batch/ai-videographer-render
      RetentionInDays: 14

  # Compute Environment - CPU optimized for FFmpeg
  ComputeEnvironmentCPU:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: ai-videographer-cpu
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: !Ref MaxvCpus
        DesiredvCpus: 0
        InstanceTypes:
          - c6i.xlarge    # 4 vCPU, 8GB - good for FFmpeg
          - c6i.2xlarge   # 8 vCPU, 16GB - faster for complex renders
          - c5.xlarge
          - c5.2xlarge
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        Tags:
          Name: ai-videographer-batch

  # Optional: GPU Compute Environment for hardware encoding
  ComputeEnvironmentGPU:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: ai-videographer-gpu
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 8
        DesiredvCpus: 0
        InstanceTypes:
          - g5.xlarge     # 4 vCPU, 16GB, 1 GPU - NVENC encoding
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        Tags:
          Name: ai-videographer-batch-gpu

  # Job Queue - tries CPU first, falls back to GPU
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: ai-videographer-render-queue
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref ComputeEnvironmentCPU
        # Uncomment to enable GPU fallback
        # - Order: 2
        #   ComputeEnvironment: !Ref ComputeEnvironmentGPU

  # Job Definition
  RenderJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: ai-videographer-render
      Type: container
      PlatformCapabilities:
        - EC2
      RetryStrategy:
        Attempts: 2
      Timeout:
        AttemptDurationSeconds: 3600  # 1 hour max
      ContainerProperties:
        Image: !Ref EcrImageUri
        JobRoleArn: !GetAtt BatchJobRole.Arn
        ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
        ResourceRequirements:
          - Type: VCPU
            Value: '4'
          - Type: MEMORY
            Value: '8192'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref RenderLogGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: render
        # Environment variables will be passed at job submission time
        # Secrets from SSM Parameter Store
        Secrets:
          - Name: SUPABASE_URL
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/supabase-url'
          - Name: SUPABASE_SERVICE_KEY
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/supabase-service-key'
          - Name: R2_ACCESS_KEY_ID
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/r2-access-key-id'
          - Name: R2_SECRET_ACCESS_KEY
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/r2-secret-access-key'
          - Name: R2_ENDPOINT
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/r2-endpoint'
          - Name: R2_BUCKET
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/r2-bucket'
          - Name: R2_PUBLIC_URL
            ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ai-videographer/r2-public-url'
        Command:
          - node
          - dist/batch-job.js

Outputs:
  ComputeEnvironmentArn:
    Description: ARN of the CPU compute environment
    Value: !Ref ComputeEnvironmentCPU
    Export:
      Name: AIVideographerComputeEnvCPU

  JobQueueArn:
    Description: ARN of the job queue
    Value: !Ref JobQueue
    Export:
      Name: AIVideographerJobQueue

  JobDefinitionArn:
    Description: ARN of the job definition
    Value: !Ref RenderJobDefinition
    Export:
      Name: AIVideographerJobDefinition

  SecurityGroupId:
    Description: Security group ID for Batch instances
    Value: !Ref BatchSecurityGroup







